apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flex-trello-docs
  namespace: flex
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://flex-docs.intern.dev.nav.no
    - https://flex-docs.ekstern.dev.nav.no
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 8080
  azure:
    application:
      allowAllUsers: false
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: '84169515-62b4-4b6f-b07c-952cbb3f20b6' #flex-infoskjerm
          - id: '7d275d5e-59a5-473d-b530-a9091b3de4c6'
    sidecar:
      enabled: true
      autoLogin: false

  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 350Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 60
  accessPolicy:
    outbound:
      external:
        - host: api.trello.com
        - host: trello.com
        - host: raw.githubusercontent.com
  envFrom:
    - secret: flex-trello-docs-trello-secrets
  env:
    - name: TRELLO_OKR_BOARD
      value: 0gO6UCsS
    - name: TRELLO_RETRO_BOARD
      value: Tx2MZJyC
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /.next/cache
